
    // AUTO GENERATED FILE FROM version_increment.py, DO NOT EDIT THIS FILE
    #ifndef VERSION
      #define VERSION "0.8.65"
    #endif
    #ifndef BUILD_TIMESTAMP
      #define BUILD_TIMESTAMP "2020-04-18 15:27:57.938117"
    #endif
    