name: Auto Wiki Responder (GitHub AI Inference)

on:
  issues:
    types: [opened]

jobs:
  respond_to_issue:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Load full wiki content
      - name: Load wiki content
        id: wiki
        run: |
          WIKI_FILE=".ai_docs_for_rag/AI-SUMMARY.md"
          if [ -f "$WIKI_FILE" ]; then
            CONTENT=$(<"$WIKI_FILE")
            echo "=== WIKI CONTENT START ==="
            echo "$CONTENT"
            echo "=== WIKI CONTENT END ==="
            echo "wiki_content<<EOF" >> $GITHUB_OUTPUT
            printf "%s\n" "$CONTENT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "No wiki file found"
            echo "wiki_content<<EOF" >> $GITHUB_OUTPUT
            echo "No wiki file found" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi


      # Generate AI response
      - name: Generate AI response
        id: ai
        uses: actions/ai-inference@v2
        with:
          model: openai/gpt-4o-mini
          prompt: |
            You are an AI assistant for the Luciferin Project. Your task is to respond to GitHub issues using the wiki content provided.

            Issue Title: ${{ github.event.issue.title }}
            Issue Body: ${{ github.event.issue.body }}

            Reference Wiki Content:
            ${{ steps.wiki.outputs.wiki_content }}

            Instructions for your reply:
            - Provide a complete and concise answer covering all relevant points from the wiki.
            - Include details on device reset procedures if applicable.
            - Close the conversation politely, explaining that if further help is needed, a human maintainer will respond.
            - Sign your reply as "Luciferin AI Assistant".
            - Format clearly and politely.

      # Post the comment to the issue
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.ai.outputs.response }}
