name: Auto Wiki Responder (GitHub AI Inference)

on:
  issues:
    types: [opened]

jobs:
  respond_to_issue:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get wiki content
      - name: Load wiki content
        id: wiki
        run: |
          WIKI_FILE=".ai_docs_for_ai/AI-SUMMARY.md"
          if [ -f "$WIKI_FILE" ]; then
            CONTENT=$(head -n 5000 $WIKI_FILE)
            echo "wiki_content<<EOF" >> $GITHUB_OUTPUT
            echo "$CONTENT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "wiki_content<<EOF" >> $GITHUB_OUTPUT
            echo "No wiki file found" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      # Generate response using GitHub AI Inference
      - name: Generate AI response
        id: ai
        uses: actions/ai-inference@v2
        with:
          model: openai/gpt-4o-mini
          prompt: |
            You are an AI assistant for the Luciferin Project. Your task is to respond to GitHub issues based on the wiki content provided.
            
            A user opened the following GitHub issue:
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}
            
            Reference wiki content:
            ${{ steps.wiki.outputs.wiki_content }}
            
            Instructions for your reply:
            - Give a complete, concise, and helpful answer covering everything relevant from the wiki.
            - Close the conversation politely: explain that if further help is needed, a human maintainer will respond as soon as possible.
            - Use a professional AI bot signature at the end: "Luciferin AI Assistant".
            
            Format your response clearly and politely.

      # Post the comment to the issue
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.ai.outputs.response }}

