name: Auto Wiki Responder (GitHub AI Inference)

on:
  issues:
    types: [opened]

jobs:
  respond_to_issue:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get wiki content
      - name: Load wiki content
        id: wiki
        run: |
          WIKI_FILE=".ai_docs_for_ai/AI-SUMMARY.md"
          if [ -f "$WIKI_FILE" ]; then
            CONTENT=$(cat "$WIKI_FILE")
            echo "wiki_content<<EOF" >> $GITHUB_OUTPUT
            echo "$CONTENT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "wiki_content<<EOF" >> $GITHUB_OUTPUT
            echo "No wiki file found" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      # Generate response using GitHub AI Inference
      - name: Generate AI response
        id: ai
        uses: actions/ai-inference@v2
        with:
          model: openai/gpt-4o-mini
          prompt: |
            You are an AI assistant for the Luciferin Project. 
            A user opened the following GitHub issue:
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}
          
            You **must answer ONLY based on the reference wiki content** provided below. 
            If the answer is not in the wiki, say politely that the user should contact a maintainer.
          
            Reference wiki content:
            ${{ steps.wiki.outputs.wiki_content }}
          
            Instructions:
            - Provide a complete, concise, and helpful answer using only the wiki.
            - Close the conversation politely, mentioning that a maintainer can help if needed.
            - Sign your answer as "Luciferin AI Assistant".


      # Post the comment to the issue
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.ai.outputs.response }}

