name: GitHub Actions CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        python --version
    - name: Install submodules 
      run: |        
        git submodule update --init
    - name: Set lib extra dirs for CI
      run: |     
        sed -i 's,^lib_extra_dirs =.*$,lib_extra_dirs = /home/runner/work/solar_station/solar_station/arduino_bootstrapper/arduino_bootstrapper,' platformio.ini
        cat platformio.ini
    - name: Run PlatformIO
      run: platformio run -e solarstation
    - name: Creating artifact from BIN file
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_solarstation.bin
        path: .pio/build/solarstation/firmware.bin
