name: GitHub Actions CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        python --version
    - name: Install submodules 
      run: |        
        git submodule update --init
    - name: Set lib extra dirs for CI
      run: |     
        sed -i 's,^lib_extra_dirs =.*$,lib_extra_dirs = /home/runner/work/solar_station/solar_station/arduino_bootstrapper/arduino_bootstrapper,' platformio.ini
        cat platformio.ini
    - name: Setup template config files
      run: |                
        cp /home/runner/work/solar_station/solar_station/arduino_bootstrapper/include/Secrets.h.template /home/runner/work/solar_station/solar_station/include/Secrets.h
        cp /home/runner/work/solar_station/solar_station/arduino_bootstrapper/include/Secrets.h.template /home/runner/work/solar_station/solar_station/arduino_bootstrapper/include/Secrets.h   
        cp /home/runner/work/solar_station/solar_station/include/Configuration.h /home/runner/work/solar_station/solar_station/arduino_bootstrapper/include/Configuration.h          
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2  
    - name: Static code analysis
      run: platformio check --verbose --severity=high --skip-packages          
    - name: Run PlatformIO
      run: platformio run -e solarstation
    - name: Creating artifact from BIN file
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_solarstation.bin
        path: .pio/build/solarstation/firmware.bin
