name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
      
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: get commit message
        run: |
           echo Commit MSG = $commitmsg             

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          python --version

      - name: Install submodules 
        run: |        
          git submodule update --init  

      - name: Setup template config files
        run: |         
          cp /home/runner/work/solar_station/solar_station/secrets.ini.template /home/runner/work/solar_station/solar_station/secrets.ini        

      - name: Static code analysis
        run: platformio check --verbose --severity=high --skip-packages   

      - name: Run PlatformIO
        run: |
          platformio run -e solarstation;
          cp .pio/build/solarstation/firmware.bin .pio/build/solarstation/Solar_Station_ESP8266_firmware.bin;

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            ${{ env.commitmsg }}
          draft: false
          prerelease: false

      - name: Release files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: .pio/build/solarstation/Solar_Station_ESP8266_firmware.bin